config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'
  resources :cocktails
  root "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show edit update destroy]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to cocktail_url(@cocktail), notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to cocktail_url(@cocktail), notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cocktail.destroy

    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:drink_type, :ingredients, :alcohol_content, :calories)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/cocktails/_cocktail.html.erb
<div id="<%= dom_id cocktail %>">
  <p>
    <strong>Drink type:</strong>
    <%= cocktail.drink_type %>
  </p>

  <p>
    <strong>Ingredients:</strong>
    <%= cocktail.ingredients %>
  </p>

  <p>
    <strong>Alcohol content:</strong>
    <%= cocktail.alcohol_content %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= cocktail.calories %>
  </p>

</div>

app/views/cocktails/_form.html.erb
<%= form_with(model: cocktail) do |form| %>
  <% if cocktail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cocktail.errors.count, "error") %> prohibited this cocktail from being saved:</h2>

      <ul>
        <% cocktail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :drink_type, style: "display: block" %>
    <%= form.text_field :drink_type %>
  </div>

  <div>
    <%= form.label :ingredients, style: "display: block" %>
    <%= form.text_field :ingredients %>
  </div>

  <div>
    <%= form.label :alcohol_content, style: "display: block" %>
    <%= form.number_field :alcohol_content %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block" %>
    <%= form.number_field :calories %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Editing cocktail</h1>

<%= render "form", cocktail: @cocktail %>

<br>

<div>
  <%= link_to "Show this cocktail", @cocktail %> |
  <%= link_to "Back to cocktails", cocktails_path %>
</div>

app/views/cocktails/index.html.erb
<h1>Cocktail</h1>

<div id="cocktails">
  <% @cocktails.each do |cocktail| %>
    <%= render cocktail %>
    <p>
      <%= link_to "Show this cocktail", cocktail %>
    </p>
  <% end %>
</div>

<div class="see-all">
    <%= link_to "View all cocktails", lists_index_path %>
</div>

app/views/cocktails/new.html.erb
<h1>New cocktail</h1>

<%= render "form", cocktail: @cocktail %>

<br>

<div>
  <%= link_to "Back to cocktails", cocktails_path %>
</div>

app/views/cocktails/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cocktail %>

<div>
  <%= link_to "Edit this cocktail", edit_cocktail_path(@cocktail) %> |
  <%= link_to "Back to cocktails", cocktails_path %>

  <%= button_to "Destroy this cocktail", @cocktail, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barettes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "nav/header" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/lists/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Lists</h1>
  <div class="cocktails">
    <%= @cocktails.each do |cocktail| %>
      <%= cocktail.drink_type %>
    <% end %>
  </div>
</div>

app/views/nav/_header.html.erb
<div class="py-5 px-5 shadow-md fixed z-50 w-full top-0">
  <div class="container mx-auto flex items-center justify-between">
    <%= link_to "Cocktail app", root_path, class: "text-2xl text-orange-500 font-bold" %>
    <nav>
      <ul class="flex items-center">
        <li class="mx-3 text-lg font-semibold hover:text-orange-500">
          <%= link_to " Alcoholic Drinks", cocktails_path %>
        </li>
        <li class="mx-3 text-lg font-semibold hover:text-orange-500">
          <%= link_to " Non-Alcoholic Drinks", cocktails_path %>
        </li>
        <li class="mx-3 text-lg font-semibold hover:text-orange-500">
        <%= link_to "New cocktail", new_cocktail_path %>
        </li>
      </ul>
    </nav>
  </div>
</div>